#!/bin/bash
#!/usr/bin/with-contenv bash

set -x 
PUID=${PUID:-911}
PGID=${PGID:-911}
PUSER=${PUSER:-abc}


addgroup --gid $PGID $PUSER
adduser --uid=$PUID --gid=$PGID --gecos "user $PUID" --disabled-password $PUSER 


echo "
-------------------------------------
   changed by ECH1965
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u $PUSER)
User gid:    $(id -g $PUSER)
-------------------------------------
"
chown $PUSER:$PUSER /app
chown $PUSER:$PUSER /config
chown $PUSER:$PUSER /defaults
chown $PUSER:$PUSER /backup
# configure ssh access
mkdir /home/ec/.ssh
chmod 700 /home/ec/.ssh
cp /config/user/authorized_keys /home/ec/.ssh
chmod 644 /home/ec/.ssh/authorized_keys
chown -R $PUSER:$PUSER /home/ec/.ssh
exit 0
