#!/bin/bash
#!/usr/bin/with-contenv bash

set -x 
PUID=${PUID:-911}
PGID=${PGID:-911}
PUSER=${PUSER:-abc}
JOB_REPO_URL=${JOB_REPO_URL:-"https://github.com/ech1965/lorath-jobs.git"}


#addgroup --gid $PGID $PUSER
adduser --uid=$PUID --gid=$PGID --gecos "user $PUID" --disabled-password $PUSER 


echo "
-------------------------------------
   changed by ECH1965
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u $PUSER)
User gid:    $(id -g $PUSER)
-------------------------------------
"
chown $PUSER:users /config
# configure ssh access
mkdir /home/$PUSER/.ssh
chmod 700 /home/$PUSER/.ssh
cp /config/user/authorized_keys /home/$PUSER/.ssh
chmod 644 /home/$PUSER/.ssh/authorized_keys
chown -R $PUSER:users /home/$PUSER/.ssh

# JOB repo is always cloned int $HOME/jobs
# Make sure repo is empty
rm -rf /home/$PUSER/jobs

# git clone
git clone $JOB_REPO_URL /home/$PUSER/jobs
chown -R $PUSER /home/$PUSER/jobs

# Install crontab

su -c  "crontab /home/$PUSER/jobs/crontab" $PUSER



exit 0
