#!/bin/bash

cp /config/ssh/* /etc/ssh
chown root:root /etc/ssh/*
chmod 600 /etc/ssh/*key
chmod 644 /etc/ssh/*pub /etc/ssh/moduli /etc/ssh/*config

echo "export LANG='en_US.UTF-8'"    > /etc/profile.d/01locale 
echo "export LANGUAGE='en_US:en'"  >> /etc/profile.d/01locale 
echo "export LC_ALL='en_US.UTF-8'" >> /etc/profile.d/01locale
exit 0
